/** Routes prerendered to dist/<path>/index.html — keep in sync with scripts/prerender-node.mjs */
export const PRERENDER_ROUTES = [
  "/",
  "/en",
  "/zh",
  "/sozdanie-sajtov",
  "/razrabotka-mvp",
  "/avtomatizaciya-biznesa",
  "/razrabotka-crm",
  "/razrabotka-lichnogo-kabineta",
  "/telegram-boty-dlya-biznesa",
  "/en/website-development",
  "/en/mvp-development",
  "/en/business-automation",
  "/en/client-portal-development",
  "/en/telegram-bot-development",
  "/en/white-label-development",
  "/mileseal",
  "/mileseal/cases/content-migration",
  "/en/mileseal",
  "/en/mileseal/cases/content-migration",
  "/zh/mileseal",
  "/zh/mileseal/cases/content-migration",
  "/projects",
  "/en/projects",
  "/zh/projects",
  "/plans",
  "/en/plans",
  "/zh/plans",
  "/about",
  "/en/about",
  "/zh/about",
  "/contacts",
  "/en/contacts",
  "/zh/contacts",
  "/partners",
  "/en/partners",
  "/zh/partners",
  "/projects/neo-terminal",
  "/projects/slotty",
  "/projects/spliton",
  "/projects/headmind",
  "/projects/logovo",
  "/en/projects/neo-terminal",
  "/en/projects/slotty",
  "/en/projects/spliton",
  "/en/projects/headmind",
  "/en/projects/logovo",
  "/zh/projects/neo-terminal",
  "/zh/projects/slotty",
  "/zh/projects/spliton",
  "/zh/projects/headmind",
  "/zh/projects/logovo",
];

export function prerenderHtmlPath(distDir, route) {
  if (route === "/") return `${distDir}/index.html`;
  const clean = route.replace(/^\/+/, "").replace(/\/+$/, "");
  return `${distDir}/${clean}/index.html`;
}
